<a href="https://colab.research.google.com/github/anujsonkar1526-coder/Data-Science-class-notes/blob/main/class8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# create dataframe

df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['raju','rani','anuj','ram'],
    'age':[25,12,56,70]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['rahul','rhea','ravi','reena'],
    'age':[15,76,50,40]
})

df3=pd.merge(df1, df2, on='id', how='inner') # inner join (dono dataframe me common wala)
df5=pd.merge(df1, df2, on='id', how='left')  # left join
df6=pd.merge(df1, df2, on='id', how='right')  # right join
df7=pd.merge(df1, df2, on='id', how='outer') # outer join
df9=pd.merge(df1, df2, how='cross') # cross join

print(df3)
print(df5)
print(df6)
print(df7)


df8=df3.rename(columns={'name_x':'table_name1'},inplace=True) # inplace df3 me hi name place karega or ager inplace nhi lgaoge to next dataframe me change hoga
print(df8)

df10=pd.concat([df1,df2]) # concat- ye table ko ek ke uper ya uper neeche join krta hai // # join- ye table  ko left ye right me join krta hai..
print(df10)
display(df10)

   id name_x  age_x name_y  age_y
0   3   anuj     56  rahul     15
1   4    ram     70   rhea     76
   id name_x  age_x name_y  age_y
0   1   raju     25    NaN    NaN
1   2   rani     12    NaN    NaN
2   3   anuj     56  rahul   15.0
3   4    ram     70   rhea   76.0
   id name_x  age_x name_y  age_y
0   3   anuj   56.0  rahul     15
1   4    ram   70.0   rhea     76
2   5    NaN    NaN   ravi     50
3   6    NaN    NaN  reena     40
   id name_x  age_x name_y  age_y
0   1   raju   25.0    NaN    NaN
1   2   rani   12.0    NaN    NaN
2   3   anuj   56.0  rahul   15.0
3   4    ram   70.0   rhea   76.0
4   5    NaN    NaN   ravi   50.0
5   6    NaN    NaN  reena   40.0
None
   id   name  age
0   1   raju   25
1   2   rani   12
2   3   anuj   56
3   4    ram   70
0   3  rahul   15
1   4   rhea   76
2   5   ravi   50
3   6  reena   40

In [ ]:
#leetcode question


import pandas as pd

def article_views(views: pd.DataFrame) -> pd.DataFrame:
    df=views.loc[views['author_id']==views['viewer_id'],['author_id']]

    sr=df['author_id'].unique() # ye hume ek series return karega or hume answer dataframe me chahiye isliye series ko dataframe me change krenge


    df= pd.DataFrame({ # dataframe me convert krne ke liye
        'id':sr
    })

    df1=df.sort_values('id')
    return df1

In [13]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['raju','rani','anuj','ram'],
    'age':[25,12,56,70]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['rahul','rhea','ravi','reena'],
    'age':[15,76,50,40]
})


df3=pd.concat([df1,df2])

df4=df3.drop_duplicates(subset=['id'],keep='first')  #drop_duplicates - jb puri row copy hogi tabhi ye us row ko drop krega copy row me sari value same honi chahiye.
display(df4)                                                # subset me hum wahi value denge jis pe hume drop apply krna hai or keep me woh value likho joh hume cahiye fist chahiye to first last chahiye to last.

   id   name  age
0   1   raju   25
1   2   rani   12
2   3   anuj   56
3   4    ram   70
2   5   ravi   50
3   6  reena   40

In [14]:
df=pd.read_csv('student_data.csv')

In [16]:
df.pivot_table(columns='placement_status',index='sleep_hours',values='exam_score',aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [18]:
df.pivot_table(columns='study_hours',index='sleep_hours',values='assignments_completed',aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844